output "iam_role_arn" {
	description = "ARN of the IAM role attached to the instance (if created)"
	value       = try(aws_iam_role.s3_upload[0].arn, null)
}

output "iam_instance_profile_name" {
	description = "Name of the IAM instance profile attached to the instance (if created)"
	value       = try(aws_iam_instance_profile.s3_upload[0].name, null)
}

output "private_key_pem" {
  description = "The private key in PEM format (if generated by Terraform)"
  value       = try(tls_private_key.main[0].private_key_pem, null)
  sensitive   = true
}
