- name: apply run
  uri:
    url: "https://{{ tfc_hostname }}/api/v2/runs/{{ run_id }}/actions/apply"
    method: POST
    headers:
      Authorization: "Bearer {{ AUTH_TOKEN }}"
      Content-Type: application/vnd.api+json
    body_format: json
    body: '{
      "comment":"This plan was reviewed and approved by CNS AAP automation."
    }
    '
    force_basic_auth: True
    validate_certs: False
    status_code:
      - 200
      - 202
    timeout: 300
  

- include_tasks: terraform_tasks/get_run_state.yml