# https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces

- name: create workspace
  uri:
    url: "https://{{ tfc_hostname }}/api/v2/organizations/{{ tfc_organization_name }}/workspaces"
    method: POST
    headers:
      Authorization: "Bearer {{ AUTH_TOKEN }}"
      Content-Type: application/vnd.api+json
    body_format: json
    body: '{
      "data": {
        "attributes": {
          "name":"{{ tfc_workspace_name }}",
          "execution-mode": "agent",
          "auto-apply": {{ tfc_api_run_module_auto_apply }},
          "allow-destroy-plan": {{ tfc_api_run_module_allow_destroy_plan }},
          "agent-pool-id": "{{ agentpool_id }}",
          "execution-mode": "agent"
        },
        "relationships": {
          "project": {
            "data": {
              "type": "projects",
              "id": "{{ project_id }}"
            }
          }
        },
        "type": "workspaces"
      }
    }'
    force_basic_auth: yes
    validate_certs: no
    status_code:
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
    timeout: 300
  register: api_result


- include_tasks: terraform_tasks/get_workspace.yml